### PR TITLE
Escape special characters in Ldap filters and enhance integration tests to cover a range of known DN and filter special characters

### LINKED ISSUE #49: Authentication returns an error when certain LDAP groups contain a '#' or other characters that are escaped in DNs
### What Happened
With the LDAP Authentication extension, if a Group that the user is in, is a Child or Grandchild of group with a name attrubute that contains a special Character. (i.e. '#') you will be presented with an LDAP error. 

This has also been raised as an OctopusServer issue here: https://github.com/OctopusDeploy/Issues/issues/7143

### **Reproduction**

**In the LDAP configuration**
Create a User "testUser" and place them in a LDAP group called "Group B". 
Make "Group B" a member of  "# Group A"

**In the Octopus instance:**
Configure an Octopus instance with LDAP. 
Set the LDAP "Nested Group Search Depth" to 2 or greater.

Create a Team and bind it to the LDAP group "Group B"
Apply some User Role Permissions.

Log into Octopus as testUser.

testUser should log in fine, but permission will not be applied.
The System Logs should return the Error Log.

### Error and Stacktrace

```
  2021-09-20 17:23:20.6990      1    145 ERROR  LDAP search for <username> failed.
  LdapLocalException: Invalid value in escape sequence "#" (87) Filter Error
```

### Workaround
Disabling nested group support by setting `Nested Group Depth` to `0` will avoid the problematic queries.  This does have the side effect that user membership in Octopus will only be attributed from groups they are direct members in rather than parent/grandparent/etc groups of those they are members in.

Alternatively if the problematic group names in the LDAP directory can be renamed to not include the [special characters](https://ldapwiki.com/wiki/DN%20Escape%20Values) that are escaped in LDAP distinguished names, that will also stop the issue occuring.

### More Information
**Internal Ticket:** https://octopus.zendesk.com/agent/tickets/76076

### PR DESCRIPTION
**Pull request by ryangribble**
Fixes #49 

### Changes

* refactored the calls to the LDAP library to go through the `LdapContext` class, providing a central place to handle common concerns more easily
* handle the already escaped reserved DN characters when a DN is used in Ldap search filters
* handle escaping of special characters in ldap search filters
* add verbose logging of Ldap queries and character escaping to enable easier debugging in future
* updated the integration test data sets and added tests for both ActiveDirectory and OpenLdap to include example groups with all the known special characters in their name

### Testing Notes

We create a heirarchical group structure consisting of a parent group, wiith child group (containing special DN characters) containing a further child group (containing special LDAP Filter characters as well as some others that are technically allowed but seem nice to include for completeness sake to make sure we handle them!) and finally a test user.

When we load groups for this test user, walkking up the parent group hierarchy we confirm that we succesfully load all 3 groups, proving not only that we no longer get Ldap errors around search filter syntax (as per the logged issue) but also that the queries/escaping actually worked correctly and we did infact issue the query "which group contains this group DN as a member"

```
Special Group Parent
|
|-- SpecialGroup , \ # + < > ; " =
    |
    |-- SpecialGroup * ( ) . & - _ [ ] ` ~ | @ $ % ^ ? : { } ! '
        |
        |-- special user
```

As seen in the wild in:

**ActiveDirectory**
image

**OpenLdap**
image

Happy days 🤣 
image

### Out of Scope
When researching Ldap character esaping, some mentions were found relating to needing to escape spaces but only when leading or trailing.  Similary there was reference to unprintable unicode characters as being able to be escaped.

Until we encounter an actual scenario where a customer has groups containing trailing/leading spaces or unprintable unicode characters, we dont want to increase complexity by attempting to escape for these...  

Note that we have already seen cyrillic/russian characters in the wild already, which worked fine, so it isnt believed to impact "normal" non english characters which we do expect many customers will be using.

### More Context
There are 2 sets of special/reserved characters in LDAP, and there are also provider specific nuances as well 🙄 

A [few characters](http://social.technet.microsoft.com/wiki/contents/articles/5392.active-directory-ldap-syntax-filters.aspx#Special_Characters) need to be escaped when used in Ldap filters.  Namely these are `*` `(` `)` `\` and `NUL`

These need to be escaped with a backslash and converting the character into a 2 digit hex code.  For example `(` can be escaped as `\29` and `\` itself as `\5C`

Meanwhile, [another set](https://ldapwiki.com/wiki/DN%20Escape%20Values) of characters must be escaped when used in DNs and a further list of special characters are documented as not requiring escaping (we include them in our tests anyway just to be sure!).  When escaping DN characters, they can be escaped either with the same above backslash + hexcode method OR they can simply be escaped with a backslash only.  For example `<` can be either ``\<` or `\3C`.
The ldap library we use actually handles this DN escaping (and different providers seem to provide either of the 2 escape formats) so we don't need to do any specific escaping ourself for these... However as a backslash is used to escape them, and a bacckslash IS is a reserved ldap filter character, we DO need to escape the backslash when using that DN in a search filter query.  That is essentially the nature of this bug 🤣 

We observed a difference in AD vs OpenLDAP in the returned escaped DN values using either of the 2 acceptable formats. 
 For example in AD a chevron is returnedby the library as `\<` but in OpenLdap it is returned as `\3C`.  This doesnt strictly matter to our auth plugin, though our integration tests do need to use these variants as the "expected" value to asset on.  Since we don't attempt to unescape any values in this plugin, it does mean these strings would be passed to Octopus and used in the mapped identities for a Team bound to dap group or a user's Ldap group memberships.  As long as the values line up (which they do) it shouldn't pose a functional issue, though it will be displayed in the identity mappings.

### CODE REVIEW

**Comment by ryangribble** [comment]
Exploratory testing against Octopus 2021.2.7727 installing test build [as a custom extension](https://octopus.com/docs/administration/server-extensibility/installing-a-custom-server-extension)

### Before

User is not mapped into parent groups where special chars are in the name

image


Searching for LDAP groups with special chars fails

image


External Group Sync shows an error for the special user

image


### After

User is correctly mapped

image


Search no longer returns errors

image


Group Sync Returns no Errors

image


Verbose log messages showing queries and escaping (set `minlevel="Debug"` in [nlog config file](https://octopus.com/docs/support/log-files#Logfiles-Changingloglevels))

image

**Comment by ryangribble** [comment]
This is the test build used to perform the above testing

[Octopus.Server.Extensibility.Authentication.Ldap.2.0.209-encoding.zip](https://github.com/OctopusDeploy/LdapAuthenticationProvider/files/7538562/Octopus.Server.Extensibility.Authentication.Ldap.2.0.209-encoding.zip)

File: source/Server/Ldap/LdapContext.cs [hunk 1]
```diff
@@ -29,12 +40,109 @@ public class LdapContext : IDisposable
 
         public string GroupNameAttribute { get; internal set; }
 
+        internal ILdapSearchResults SearchUsers(string searchToken)
```
Comment (tothegills) [inline source/Server/Ldap/LdapContext.cs:43]: Nicely refactored to hide the connection

**Review by tothegills — APPROVED** [review]
Includes good test coverage and the fact the customer is currently using it add to the confidence

**Comment by tothegills** [comment]
Relates to https://github.com/OctopusDeploy/Issues/issues/7143

**Comment by danefalvo** [comment]
2021.3.x compatible DLL
[Octopus.Server.Extensibility.Authentication.Ldap.zip](https://github.com/OctopusDeploy/LdapAuthenticationProvider/files/7896168/Octopus.Server.Extensibility.Authentication.Ldap.zip)
